### PR TITLE
Add short description to README

### PR DESCRIPTION
**Pull request by Jonas-I**
Updating initial README.
> We create an Android application using the Twitch API.

### CODE REVIEW

**Review by alphanyang — COMMENTED** [review]
great job team

**Review by josh-improgo — CHANGES_REQUESTED** [review]
Please be more specific about what kind of Android application you are creating

**Review by josh-improgo — APPROVED** [review]
LGTM! 👍

**Review by alphanyang — APPROVED** [review]
great job team

**Pull request merged**
